### ISSUE TITLE
SPRINT3: FRONTEND: Persistence of login information

### ISSUE THREAD

**Issue by Nwitz** [SOEN341-winter2019/Team-Project#101]
Persistence is necessary to allow a user to see the correct profile and dashboard following login. Cookies may be the best approach to this. The cookie storing the username will be crucial for all `POST` and `GET` requests to the server as this will allow the server to know exactly which user to return the date for.

This is necessary for Issue #87, Sprint3: FRONTEND: Profile Page, as the login will provide the correct data to access a specific profile page, unique to the user.

**Comment by Nwitz** [comment]
This might turn into a backend issue. It is still undecided if username will be persisted in the session in frontend, or if backend will handle keeping track of user while login occurs.

**Comment by rickyelopez** [comment]
This is now being discussed in #127. Closing this issue
