### ISSUE TITLE
SPRINT3: FRONTEND: Tweet template and functions

### ISSUE THREAD

**Issue by Nwitz** [SOEN341-winter2019/Team-Project#112]
As per issue #97 SPRINT3: FRONTEND: Feed creation, the feed will be composed of tweets, each tweet will need to fill a similar template, allowing users to: 
- View a profile picture of the author
- Read the content of the tweet
- Navigate to the author's page
- Like the tweet

Other options can be included such as 
- Time stamp
- Retweet button
- Comment button

**Comment by rickyelopez** [comment]
All features implemented, closing issue.
