### ISSUE TITLE
Sprint4: BACKEND: Additional Feature: Retweet

### ISSUE THREAD

**Issue by fjodoin** [SOEN341-winter2019/Team-Project#114]
STORY POINT 3

Backend User Story for Additional Feature 2: Retweet - To be confirmed with Client (TA)

"As a User, I would like to have the option to Retweet a given Tweet so that I may give credit to the original Tweeter."

_Additional feature changed for #134 and #135_

**Comment by rickyelopez** [comment]
feature dropped, closing issue.
