### ISSUE TITLE
Sprint4: BUG: Highlighted "Like" feature

### ISSUE THREAD

**Issue by fjodoin** [SOEN341-winter2019/Team-Project#125]
Part of Sprint3 BUGS: #124 

The "Like" feature icon must be highlighted if a user has already liked a certain Tweet (OK)
The Database receives the "Like" and increments the Tweet's "Like" counter. (OK)

**The "Like" feature icon must REMAIN highlighted if a user refreshed the page / returns to the page** (BUG) -- _Fix and test once sessions are implemented  (~March 22)_

**Comment by rickyelopez** [comment]
resolved in the above PR
