### ISSUE TITLE
SPRINT4: FRONTEND: connect ensure cookies fill useful variables

### ISSUE THREAD

**Issue by Nwitz** [SOEN341-winter2019/Team-Project#149]
Currently cookies fill their own variables, but we need to be able to access the cookie information within the jQuery, this means either changing the variable in Jquery or using a global variable. 

This will officially remove the hard coded usernames and replace them with the stored Cookie, dynamic equivalent.

**Comment by rickyelopez** [comment]
feature fully implemented, tested, and accepted
