### ISSUE TITLE
Sprint1-07: FRONTEND

### ISSUE THREAD

**Issue by fjodoin** [SOEN341-winter2019/Team-Project#23]
Issue acting as an EPIC of Sprint 1's; **JavaScript**

User Story: [Information on what the Big Ideas and features for the frontend are]

1- "Tweeting", Posting a comment
2- "Like" feature
3- "Follow" feature

Features above will be opened as sub-issues; include link (#issue_reference_number") to this issue in description.

**Comment by fjodoin** [comment]
fahfbuiauoij[f ufnunu #27

**Comment by fjodoin** [comment]
If Frontend team comes up with more features necessary; please comment below.
**Make sure to refer issues opened related to the features of this EPIC in the comment-section below**

**Comment by fjodoin** [comment]
Issue opened regarding TWEET FEATURE; refer to tag above (#33)

**Comment by Jacobian8** [comment]
all issued regarding this epic have been reviewed and closed. New issued will be opened this week when implementing said features.
