### ISSUE TITLE
Sprint1-02: Updating Contact_Information.md with known Programming Languages

### ISSUE THREAD

**Issue by fjodoin** [SOEN341-winter2019/Team-Project#3]
Following up on Team Meeting 1 (recorded in Meetings.md);

Please update the Contact_Information.md file with **your programming language capacities**;

Once this is complete, we can decide as a team which language our project will be written in.

**PLEASE COMMENT WHEN YOU ARE DONE UPDATING YOUR INFORMATION**

**Comment by fjodoin** [comment]
Done!

**Comment by Synneva** [comment]
Done 2/10

**Comment by fjodoin** [comment]
Noah is done 3/10

**Comment by fjodoin** [comment]
Patricia is done 4/10

**Comment by rickyelopez** [comment]
Done

**Comment by johnstonstott** [comment]
Done 6/10

**Comment by GD-DevFlow** [comment]
Done 7/10

**Comment by Jacobian8** [comment]
Done 8/10

**Comment by EspressoCode** [comment]
Done 9/10

**Comment by fjodoin** [comment]
Mehrdad is done 10/10
