### ISSUE TITLE
Sprint1: DATABASE: Tweet Feature

### ISSUE THREAD

**Issue by fjodoin** [SOEN341-winter2019/Team-Project#31]
Feature to be discussed by the Database team; as per #24

**Comment by rickyelopez** [comment]
Ok so for tweets we're probably going to need an ID, content, and timestamp at the very least. Anything else?

**Comment by fjodoin** [comment]
I think those three points will be great; if a tweet always contains these three items they should be easily retrievable. 

What about if tweet a contained a flag for the "like" option?

**Comment by patnunes** [comment]
I think tweets should also have a user_id (as a foreign key) to relate back to the user who posted the tweet, as well as everything you mentioned. 

As for a flag option I think likes should be a separate table, that consists of tweet_id (foreign key), and user_id (foreign key).

**Comment by Mehrdadmaskull** [comment]
I agree with @patnunes on having a separate table for likes. And also for the number of likes, instead of another column, I also suggest using the 'count' method instead.

Does anyone want to be responsible for making the RDBMS model? A simple table or drawing just so we can discuss it?

**Comment by patnunes** [comment]
For the likes_counter my idea was to use a procedure, thus whenever a user likes something this event would trigger the procedure. However, I'm not entirely sure which way would be more efficient. 

I wouldn't mind creating a mock design for the database. 

Also I think to simplify things Tweets can have comments but we should only allow one sub-level of comments. (So for instance you cant comment on someone else's comment and create another sub-thread, kind of like Facebook).

**Comment by GD-DevFlow** [comment]
Hey guys I don't have much to contribute yet as I'm not familiar with Database architecture but I will be next week.

**Comment by rickyelopez** [comment]
I agree with @patnunes and @Mehrdadmaskull. Closing this issue, we'll open a new one when implementing this feature.
