### ISSUE TITLE
Sprint1: BACKEND: Tweet Feature

### ISSUE THREAD

**Issue by fjodoin** [SOEN341-winter2019/Team-Project#32]
Feature to be discussed by the Backend team; as per #22

**Comment by rickyelopez** [comment]
So we're going to need to be able to push tweets into the DB on request from the frontend. Do we want to support tweet deletion/editing?

**Comment by fjodoin** [comment]
@rickyelopez If supporting the deletion/editing isn't too complicated lets keep it in mind.

**Comment by EspressoCode** [comment]
so if somebody deletes his/her own tweet that would be complicated for sure as we have to decide what we will do for the retweets and comments on that tweet (comments will be deleted but should we keep or delete retweets?)

**Comment by Synneva** [comment]
All shares should be deleted if the original post is, in my opinion

**Comment by rickyelopez** [comment]
So: we need methods to push tweets into the DB, to allow editing for a short period, and to delete the tweet (and all retweets).

Closing this issue.
