### ISSUE TITLE
Sprint1: FRONTEND: Tweet Feature

### ISSUE THREAD

**Issue by fjodoin** [SOEN341-winter2019/Team-Project#33]
Feature to be discussed by the Frontend team; as per #23

**Comment by Nwitz** [comment]
Tweet feature will require a UI where a user can enter a short paragraph. If interest is to keep exactly like twitter a character limit will need to be imposed and handled with checks using JS before sending to backend / database. We can also design this section to allow for other features such as tagging using the 
"@" symbol.

**Comment by johnstonstott** [comment]
Like real Twitter, we may want to allow users to include hashtags in posts. It will be easy for users to view a collection of posts related to a specific topic. If not, we could consider another way to categorize posts (for example, a more simple implementation may be pre-set categories such as "sports", "funny", "animals", etc. which users can add to their posts if they want to categorize them).

**Comment by Jacobian8** [comment]
Issue closed: A new one will be open when we implement the feature and start the layout of the website.
