### ISSUE TITLE
Sprint1: FRONTEND: Like Feature

### ISSUE THREAD

**Issue by Nwitz** [SOEN341-winter2019/Team-Project#34]
Button connected to back-end allowing like to be saved for specific account. Button in this particular case generally acts as toggle, and will reverse the result when clicked a second time. This can be done using a simple boolean method which returns not(likeVariable).

**Comment by Nwitz** [comment]
#23

**Comment by Jacobian8** [comment]
issue closing. A new one will be open when we implement the feature and create the skeleton of the website.
