### ISSUE TITLE
Sprint1: DATABASE: Like Feature

### ISSUE THREAD

**Issue by rickyelopez** [SOEN341-winter2019/Team-Project#36]
Per #24, we need to have a "like" feature. What would be the best way to store all of the likes for each tweet? Surely making a separate table for each one would use up to much space, right? And by the same token, having one column in the table for "likes" where we just append all the usernames would result in a massive entry. Any other good options?

**Comment by patnunes** [comment]
Since this would be a many-to-many relationship, users can like multiple posts (tweets in this case) and a post can be liked by many users we could simply create an intermediate table. Likes would then be its own table that consists of two foreign keys which would be post_id and user_id.

**Comment by rickyelopez** [comment]
Ok, that should work fine. Closing this issue because it's settled.
