### ISSUE TITLE
Sprint1: DATABASE: Follow Feature

### ISSUE THREAD

**Issue by patnunes** [SOEN341-winter2019/Team-Project#39]
As per #24, for the follow feature of the database: a user can follow many users and a user may have many following users, which results in a many-to-many relationship. In order to implement this I was thinking of having a table User which would contain all necessary user information and then a separate table Follower which would contain user_id and follower_id as foreign keys to user_id in the User table. This way adding/deleting a follower just requires either an insert or delete. 

Please let me know if anyone has other ideas/suggestions! 

![follower db design](https://user-images.githubusercontent.com/10131624/51860347-63f11d00-2307-11e9-9a32-becd615d7e9e.PNG)

**Comment by Jacobian8** [comment]
Hey!, this is great and is excatly how it should be done. Just one note though. I think the arrows need to be inverted. 
The user table has a primary key which is the user_id and the follower had a foreign key which is the follower_id like you said. 
So i think that the arrow needs to be pointing from the primary_key to the foreign_key

**Comment by patnunes** [comment]
Thanks for pointing that out! I will keep that in mind when creating a mock up design for the database.

**Comment by rickyelopez** [comment]
Closing this issue because it's settled.
