### ISSUE TITLE
Sprint1: FRONTEND: Follow Feature

### ISSUE THREAD

**Issue by johnstonstott** [SOEN341-winter2019/Team-Project#40]
As per #23, site needs a feature allowing users to follow other users. User can press a "follow" button if they want to follow someone, or click again to unfollow. As mentioned on Slack, a "tweet" will have a follow action so users can follow the poster of the tweet. We should also give users the opportunity to follow when they are viewing another user's profile. Feel free to comment if you have any other suggestions/input!

**Comment by Nwitz** [comment]
This seems right and should work, the logic for both follow buttons will be the same.
