### ISSUE TITLE
Sprint2: FRONTEND: User Profile Creation

### ISSUE THREAD

**Issue by fjodoin** [SOEN341-winter2019/Team-Project#43]
STORY POINT: 7

It will be necessary to have a User Profile Creation sequence in order to make our core features usable.
- You must be a user in order to "Tweet", "Like", and/or "Follow".

**Comment by Nwitz** [comment]
When creating a user profile, the user should be met with a screen allowing necessary information to be entered: Username (must contact server to see if already in use), email and password. 

This sign in screen can be basic with text fields appearing on a centered form.

**Comment by fjodoin** [comment]
@Nwitz We should open a new issue: Sign in Screen which refers to this EPIC.

What do you think?

**Comment by fjodoin** [comment]
Something like: Sprint2: FRONTEND: Sign in Screen (Label is as a task and assign it to Frontend Team)

**Comment by Nwitz** [comment]
You are right, will do.

**Comment by Nwitz** [comment]
In the simplest terms, this story is complete, a user is met with a UI allowing them to enter information required to create a profile. There is no profile customization here, but at the current version a user can create a profile, and log into it. No other screens exist however.

**Comment by fjodoin** [comment]
Closed: Sprint 2 Over - Summary above
