### ISSUE TITLE
Sprint2: DATABASE: Tweet Feature Architecture

### ISSUE THREAD

**Issue by fjodoin** [SOEN341-winter2019/Team-Project#48]
Deciding upon core feature "Tweet" architecture;

**Comment by Jacobian8** [comment]
Improved class diagram
![class_diagram_updated](https://user-images.githubusercontent.com/38959026/52436256-dc16ca00-2ae1-11e9-827d-c5fb3468a949.png)

**Comment by rickyelopez** [comment]
All tables created, reopen issue if required.

**Comment by Jacobian8** [comment]
UPDATED class diagram to include tweet comments and parents

![class_diagram_updated](https://user-images.githubusercontent.com/38959026/52438072-6fea9500-2ae6-11e9-9598-bee16e0db4d2.png)
