### ISSUE TITLE
Sprint2: DATABASE: Confirm server connectivity: HIGH Priority

### ISSUE THREAD

**Issue by rickyelopez** [SOEN341-winter2019/Team-Project#51]
USER STORY POINT: 5

Hi Database,

Can any of you please double check that the SQL server I set up is accessible over the internet? Credentials and connection info have been shared on Slack.

**Comment by fjodoin** [comment]
as per #44

**Comment by rickyelopez** [comment]
Server connectivity has been confirmed functional. Closing this issue.
