### ISSUE TITLE
Sprint2: BACKEND: Configure Django environment

### ISSUE THREAD

**Issue by rickyelopez** [SOEN341-winter2019/Team-Project#64]
The Django environment needs to be configured so that it will work with the files that frontend is generating

**Comment by fjodoin** [comment]
Changed form HIGH to low Risk Level; i confused Configuration with Creation - Configuring doesnt actually change the parameters; there is no danger of "breaking" our system with this issue.

**Comment by rickyelopez** [comment]
Most recent commit resolves issue. The backend environment is now properly set up to reference the front end files. Closing this issue.
