### ISSUE TITLE
Sprint1-04: Deciding on Programming Language(s)

### ISSUE THREAD

**Issue by fjodoin** [SOEN341-winter2019/Team-Project#7]
Please input your suggestions on which language(s) we should use along with a brief (1-sentence) explanation about your choice below; this Issue will be considered as a Meeting and will be recorded as **Meeting2**.

_Consult the Contact_Information.md file for each member's Programming Language knowhow._

**Comment by rickyelopez** [comment]
Done (1/10)

**Comment by fjodoin** [comment]
Done (2/10)

**Comment by Synneva** [comment]
Done (3/10)

**Comment by patnunes** [comment]
Done (4/10)

**Comment by johnstonstott** [comment]
Done (5/10)

**Comment by EspressoCode** [comment]
Done (6/10)

**Comment by Nwitz** [comment]
Done (7/10)

**Comment by fjodoin** [comment]
10/10 participated (Nice job team)

Finalization on Language will be done Friday before / after meeting

**Comment by fjodoin** [comment]
Language decided on; refer to Meeting3 Issue #28
