### ISSUE TITLE
Sprint2: BACKEND: Sign-in feature

### ISSUE THREAD

**Issue by EspressoCode** [SOEN341-winter2019/Team-Project#74]
We need to compare and match the username and password from user inputs to what we have in database, and respond to the user with a message, which would be either "You logged in successfully" or "The username/password was wrong".

**Comment by rickyelopez** [comment]
what's the status on this?

**Comment by rickyelopez** [comment]
this needs to be open for now

**Comment by rickyelopez** [comment]
Feature has been implemented, see the above commit.
