### ISSUE TITLE
Sprint1-05: Pull Request

### ISSUE THREAD

**Issue by fjodoin** [SOEN341-winter2019/Team-Project#9]
Sprint 1 requires everyone to produce a "pull request" to then be merged; we have all been **directly modifying the master** as opposed to creating a branch. Please do the following in order to meet Sprint1 requirement:

**Task:**Modify the indent of your name in README.md to match:
 - First Lastname

When finished, **create a branch by choosing;** *Create a **new branch** for [...]* 
![capture](https://user-images.githubusercontent.com/46529922/51633065-ce2c4b00-1f1e-11e9-9df7-1bd1e254f97c.JPG)
 - Do not use *Commit directly to **master branch***

I will merge your changes; 

If you have any questions, please present them in this issue's comment section

**Comment by fjodoin** [comment]
2/10 done

**Comment by rickyelopez** [comment]
Ricky 3/10 done

**Comment by EspressoCode** [comment]
Hossein 4/10 done

**Comment by Nwitz** [comment]
Noah 6/10 done

**Comment by fjodoin** [comment]
Mehrdad done, 7/10

**Comment by patnunes** [comment]
Patricia 8/10 done

**Comment by Jacobian8** [comment]
Jacob done 9/10

**Comment by fjodoin** [comment]
1st Pull Request by entire team COMPLETE; 

Remarks: Must remember to **Modify Title of branch / commit ALONG WITH adding a short description**; i.e. title: "Updated README.md; Indent fixed", description: "As per issue #(issue tag ID), formatting problem was resolved with an indent fix.
